name = "aws-ses-fastmcp-proxy"
main = "cloudflare-proxy.js"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

# Environment variables for production
[env.production]
vars = { }

# Secrets to set via CLI:
# wrangler secret put FASTMCP_SERVER_URL --env production
# wrangler secret put API_KEY --env production

# Example deployment commands:
# wrangler deploy --env production
# wrangler secret put FASTMCP_SERVER_URL --env production
# wrangler secret put API_KEY --env production

[build]
command = ""

# Custom domains (optional)
# [[env.production.routes]]
# pattern = "api.yourdomain.com/*"
# zone_name = "yourdomain.com"